matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd backend
    - language: node.js
      node_js: "12.0"
      before_script:
        - cd frontend
      script:
        - npm i
        - npm run build
