matrix:
  include:
    - language: java
      before_script:
        - cd backend
      script:
        - mvn clean install
    - language: node.js
      node_js: "12.0"
      before_script:
        - cd frontend
      script:
        - npm i
        - npm run build
